language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
  global:
  - secure: nOrKqaiTs1ayJNpUAdlt8meNwjQSZ4Khy8I9MoVWiKvvKFNbVmfTB/mpBk/a2sSQVJfemAZkQSnjjAoEj3mg4jhasbpcV8HWqOD2QYfjQmuEnm5Xbaf3nrnnS8KVJlRNVcbBQPosYaCp+uqS4nq7J0zl8yPtkCzuIyjY5YPS0jg=
  - secure: EgRr0EMenk+WktTGgMbtmx5iFk5E3BJpd0oWa1Lz2UqJlOLNkqlE2rhdu2Ao8BxA6WMk3O/vBR0PQPCdQPo1oFgP7D80s9PVrmHdjfo1Ptt5QUmw2rzZ44h9/f7GrBPdeGp3iPcWgiRm1yWdam/FZdZS+CcCEmCMwGtuNFGd31Y=
before_install:
- npm install -g npm
before_script:
- npm install -g bower grunt-cli
- npm install
- bower install
script: grunt test-ci
after_success: coveralls:all